import {
  CrimeStatus,
  CrimeType,
  CrimeTracker,
} from "@/modules/trackstatus/types";

export const mockCrimeReports: CrimeTracker[] = [
  {
    id: "CR-001",
    crimeType: CrimeType.Robbery,
    location: "Lagos Mainland, Nigeria",
    dateReported: "2025-09-28",
    timeReported: "08:45 AM",
    status: CrimeStatus.Resolved,
  },
  {
    id: "CR-002",
    crimeType: CrimeType.Fraud,
    location: "Abuja, Nigeria",
    dateReported: "2025-09-30",
    timeReported: "02:15 PM",
    status: CrimeStatus.InProgress,
  },
  {
    id: "CR-003",
    crimeType: CrimeType.Assault,
    location: "Port Harcourt, Nigeria",
    dateReported: "2025-10-02",
    timeReported: "11:30 AM",
    status: CrimeStatus.PendingReview,
  },
  {
    id: "CR-004",
    crimeType: CrimeType.Kidnapping,
    location: "Kaduna, Nigeria",
    dateReported: "2025-10-01",
    timeReported: "09:00 PM",
    status: CrimeStatus.Rejected,
  },
  {
    id: "CR-005",
    crimeType: CrimeType.Theft,
    location: "Ibadan, Nigeria",
    dateReported: "2025-09-25",
    timeReported: "07:20 AM",
    status: CrimeStatus.Resolved,
  },
  {
    id: "CR-006",
    crimeType: CrimeType.Robbery,
    location: "Enugu, Nigeria",
    dateReported: "2025-09-29",
    timeReported: "04:55 PM",
    status: CrimeStatus.InProgress,
  },
  {
    id: "CR-007",
    crimeType: CrimeType.Fraud,
    location: "Benin City, Nigeria",
    dateReported: "2025-09-23",
    timeReported: "01:40 PM",
    status: CrimeStatus.PendingReview,
  },
  {
    id: "CR-008",
    crimeType: CrimeType.Assault,
    location: "Jos, Nigeria",
    dateReported: "2025-09-20",
    timeReported: "10:05 PM",
    status: CrimeStatus.Rejected,
  },
  {
    id: "CR-009",
    crimeType: CrimeType.Others,
    location: "Abeokuta, Nigeria",
    dateReported: "2025-09-27",
    timeReported: "06:10 PM",
    status: CrimeStatus.InProgress,
  },
  {
    id: "CR-010",
    crimeType: CrimeType.Theft,
    location: "Uyo, Nigeria",
    dateReported: "2025-09-19",
    timeReported: "09:25 AM",
    status: CrimeStatus.Resolved,
  },
];
